//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDict
{
    using System;
    using System.Collections.Generic;
    
    public partial class Terms
    {
        public int ID { get; set; }
        public string Term { get; set; }
        public string Description { get; set; }
        public string Source { get; set; }
    }
}
